Do not build-test on arm64 (HW dependent)
It seems that depending on the builder environment we get all tests
failing often with:
   ERROR: This system does not support "CRC32".
   Please check that RTE_MACHINE is set correctly.
   EAL: FATAL: unsupported cpu type.
   EAL: unsupported cpu type.

We've had no tests (for them being too HW dependent for a long time)
and having them reliable for x86 at least is good, but disabling them
for arm64 helps to not make this flaky and a source of pain.

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>